swift 3.1 changes
davidungar/miniPromiseKit pull request #4
Opened 2017-03-30 08:34 UTC by VolkerBb

After the update to Swift 3.1 I stumbled upon an EXC_BAD_ACCESS in the init call of the Promise extension. This minor change fixes the bug for me.

2017-03-31 18:03 UTC, davidungar requested changes
Thanks for your review and great work finding a fix! My only reservation is the misspelling in the comment: 'fulfull' instead if 'fulfill'. I can't tell you how many times I make the same mistake! Would you like to fix it? Or would you prefer I push the same change?

2017-04-01 13:10 UTC, VolkerBb commented
Sorry about that. I've corrected spelling in the comment. Thank you, David.

2017-04-01 13:50 UTC, merged

2017-04-01 13:52 UTC, davidungar commented
Thank you again, Volker. I appreciate it.

2017-04-01 14:07 UTC, davidungar commented
No problem. I’ve merged in your pull request. Thanks again, Volker.

> On Apr 1, 2017, at 6:10 AM, Volker Bublitz <notifications@github.com> wrote:
> 
> Sorry about that. I've corrected spelling in the comment. Thank you, David.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/davidungar/miniPromiseKit/pull/4#issuecomment-290919163>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAcJ0D60vKHrUgJDSo0gYgPn9UhIoH-dks5rrkyzgaJpZM4MuCD6>.
>